import type {Metadata} from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";
import React from "react";
import ThemeRegistry from "@/theme/ThemeRegistry";
import {Toaster} from "react-hot-toast";

const montserrat = Montserrat({ subsets: ["latin"] });

// @ts-ignore
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html>
          <body className={montserrat.className} suppressHydrationWarning={true}>
          <ThemeRegistry>{children}</ThemeRegistry>
            <Toaster
                toastOptions={{
                    duration: 10000,
                }}
            />
          </body>
      </html>
  );
}
